services:
  app-nestjs:
    image: app-nestjs-image:latest
    container_name: app-nestjs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-postgres:5432/architecture
      PORT: 3000
      HOSTNAME: ${HOSTNAME}
      NODE_ENV: ${NODE_ENV}
    networks:
      - nestjs-network
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:16-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # ${DB_USER} inside .env
      POSTGRES_PASSWORD: postgres # ${DB_PASSWORD} inside .env
      POSTGRES_DB: architecture # ${DB_NAME} inside .env
      POSTGRES_INITDB_ARGS: '-E UTF8' # Define o encoding dos dados do banco de dados
      TZ: 'UTC' # Define o horário do Sistema Linux (Alpine)
      PGTZ: 'UTC' # Define o timezone da sessão do Postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d architecture']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
